#cloud-config
autoinstall:
  version: 1
  interactive-sections:
    - network
    - storage
  locale: en_US
  storage:
    layout:
      name: lvm
  identity:
    hostname: test
    realname: 'Default Admin user'
    username: admin
    password: '$y$j9T$Tv6FavKqhsv603nzZWMwQ/$qx7vdM23cIgIX3jkTuR7lZ7IiXHwTEkCVVKwV9x2dsC'
  ssh:
    install-server: yes
    allow-pw: yes
  user-data:
    disable_root: false
    users:
      - name: user
        gecos: 'Standard User'
        groups: adm, cdrom, dip, lxd, plugdev, netdev, kvm, lpadmin, dialout, libvirt, docker
        passwd: '$y$j9T$N5JoGTfh1YxoU1WS2SneV.$RrrGHBClDxuZgGK7DRPkcpiv9r/ywsKAC7Kr7ZNo474'
        shell: /bin/bash
        lock_passwd: false
    runcmd:
      - [sed, -i, 's/\GRUB_CMDLINE_LINUX_DEFAULT=\"/&quiet splash /', /etc/default/grub]
      - [sed, -i, 's/GRUB_TIMEOUT=0/GRUB_TIMEOUT=5/g', /etc/default/grub]
      - [sed, -i, 's/GRUB_TIMEOUT_STYLE=hidden/GRUB_TIMEOUT_STYLE=countdown/g', /etc/default/grub]
      - [sed, -i, 's/managed=false/managed=true/g', /etc/NetworkManager/NetworkManager.conf]
      - [mkdir, -p, /autoinstall/backup]
      - [mv, /usr/lib/NetworkManager/conf.d/10-globally-managed-devices.conf, /autoinstall/backup]
      - [touch, /usr/lib/NetworkManager/conf.d/10-globally-managed-devices.conf]
      - |
        cat << EOF > /etc/netplan/50-cloud-init.yaml
        network:
          version: 2
          renderer: NetworkManager
        EOF
      - |
        cat << EOF > /etc/timezone
        Europe/Budapest
        EOF
      - [ln, -sf, /usr/share/zoneinfo/Europe/Budapest, /etc/localtime]
      - [dpkg-reconfigure, -fnoninteractive, tzdata]
      - [netplan, apply]
      - [update-grub]
      - [snap, connect, bitwarden:password-manager-service]
      - [systemctl, reboot]
  apt:
    sources:
      google-chrome-repo:
        source: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        keyid: EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796
      virtualbox-repo:
        source: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian noble contrib
        keyid: B9F8D658297AF3EFC18D5CDFA2F683C52980AECF
      docker-repo:
        source: deb [arch=amd64] https://download.docker.com/linux/ubuntu noble stable
        keyid: 8D81803C0EBFCD88
      azluxfr:
        source: deb [arch=amd64] http://packages.azlux.fr/debian stable main
        keyid: 98B824A5FA7D3A10FDB225B7CA548A0A0312D8E6
      obs-studio:
        source: ppa:obsproject/obs-studio
  snaps:
    - name: firefox
    - name: brave
    - name: thunderbird
    - name: slack
    - name: bitwarden
    - name: code
  packages:
    - libreoffice
    - kubuntu-desktop
    - mc
    - vlc
    - ffmpeg
    - google-chrome-stable
    - virtualbox
    - virt-manager
    - htop
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    - docker-ctop
    - mpv
    - wireguard
    - network-manager-openvpn
    - iperf3
    - ansible
    - gimp
    - wireshark
    - net-tools
    - dnsutils
    - whois
    - kazam
    - tilix
    - tcpdump
    - gimp
    - python3-venv
    - obs-studio
  late-commands:
    - curtin in-target --target=/target -- systemctl disable systemd-networkd systemd-networkd.socket
    - curtin in-target --target=/target -- systemctl enable docker libvirtd NetworkManager
