#cloud-config
autoinstall:
  version: 1
  interactive-sections:
    - network
    - identity
    - storage

  locale: "en_US.UTF-8"
  refresh-installer:
    update: true
  
  ssh:
    install-server: true
    allow-pw: true
  codecs:
    install: true
  drivers:
    install: true
  kernel: 
    flavor: hwe
  updates: all

  packages:
    - mc
    - htop
    - google-chrome-stable


