#cloud-config
autoinstall:
  version: 1
  interactive-sections:
    - network
    - storage
  locale: en_US
  storage:
    layout:
      name: lvm
  identity:
    hostname: test
    realname: 'Default Admin user'
    username: admin
    password: '$y$j9T$Tv6FavKqhsv603nzZWMwQ/$qx7vdM23cIgIX3jkTuR7lZ7IiXHwTEkCVVKwV9x2dsC'
  ssh:
    install-server: yes
    allow-pw: yes
  user-data:
    disable_root: false
    users:
      - name: user
        gecos: 'Standard User'
        groups: adm, cdrom, dip, lxd, plugdev, netdev, kvm, lpadmin, dialout
        passwd: '$y$j9T$bOCNUW5m1vZBiWlY96qlQ.$/NfEohbNgJSeVg51pp.cnJhTVrzKcy8.8MWGgMb6R41'
        shell: /bin/bash
    runcmd:
      - [usermod, -aG, libvirt, user]
      - [usermod, -aG, docker, user]
      - [systemctl, reboot]
  apt:
    sources:
      google-chrome-repo:
        source: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        keyid: EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796
      virtualbox-repo:
        source: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian noble contrib
        keyid: B9F8D658297AF3EFC18D5CDFA2F683C52980AECF
      docker-repo:
        source: deb [arch=amd64] https://download.docker.com/linux/ubuntu noble stable
        keyid: 8D81803C0EBFCD88
  snaps:
    - name: firefox
    - name: slack
    - name: bitwarden
    - name: code
  packages:
    - libreoffice
    - kubuntu-desktop
    - thunderbird
    - mc
    - vlc
    - ffmpeg
    - google-chrome-stable
    - virtualbox
    - virt-manager
    - htop
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  late-commands:
    - curtin in-target --target=/target -- systemctl disable systemd-networkd systemd-networkd.socket
    - curtin in-target --target=/target -- systemctl enable docker libvirtd NetworkManager
    - curtin in-target --target=/target -- rm /etc/netplan/50*.yaml
    - curtin in-target --target=/target -- curl https://furit.systems/nm-netplan.sh -o /nm-netplan.sh
    - curtin in-target --target=/target -- chmod +x /nm-netplan.sh
    - curtin in-target --target=/target -- /nm-netplan.sh
    - curtin in-target --target=/target -- rm /nm-netplan.sh
    - curtin in-target --target=/target -- netplan generate
    - curint in-target --target=/target -- netplan apply
